export const assetBase = '/courses/ai-with-python/lesson-04';
export const chapters = [
  { id: 'look', number: '01', title: '望：看懂战报' },
  { id: 'smell', number: '02', title: '闻：读取线索' },
  { id: 'analyze', number: '03', title: '切：分析嫌疑' },
] as const;

export const scenes = [
  { id: 'l4-cover', chapter: 'look', title: '数据小侦探' },
  { id: 'l4-opening', chapter: 'look', title: '城堡守住了，谁在指挥？' },
  { id: 'l4-suspects', chapter: 'look', title: '先认识调查名单' },
  { id: 'l4-roadmap', chapter: 'look', title: '跟着《唐探1900》学探案' },
  { id: 'l4-look-cover', chapter: 'look', title: '望：看懂战报' },
  { id: 'l4-data-kinds', chapter: 'look', title: '同一只狗，可以记录什么？' },
  { id: 'l4-categories', chapter: 'look', title: '分类数据：它属于哪一类？' },
  { id: 'l4-quantities', chapter: 'look', title: '数值数据：有多少、有多大？' },
  { id: 'l4-all-records', chapter: 'look', title: '先把全部战报看一遍' },
  { id: 'l4-types', chapter: 'look', title: '哪些能分类，哪些能计算？' },
  { id: 'l4-table', chapter: 'look', title: '一行、 一列、一个值' },
  { id: 'l4-structure', chapter: 'look', title: '同样的记录，怎样更好找？' },
  { id: 'l4-question', chapter: 'look', title: '这份战报能回答什么？' },
  { id: 'l4-practice-01', chapter: 'look', title: '先写下你的调查办法' },
  { id: 'l4-smell-cover', chapter: 'smell', title: '闻：读取线索' },
  { id: 'l4-pandas-intro', chapter: 'smell', title: '海龟先生，请来熊猫博士' },
  {
    id: 'l4-data-structures',
    chapter: 'smell',
    title: '熊猫博士的两种数据工具',
  },
  { id: 'l4-pandas', chapter: 'smell', title: '请来处理表格的帮手' },
  { id: 'l4-load', chapter: 'smell', title: '把 CSV 读成一张表' },
  { id: 'l4-info', chapter: 'smell', title: '先检查这份记录' },
  { id: 'l4-series', chapter: 'smell', title: '用代码取出一列' },
  { id: 'l4-row', chapter: 'smell', title: '查看第一条进攻记录' },
  { id: 'l4-select', chapter: 'smell', title: '只留下当前需要的列' },
  { id: 'l4-practice-02', chapter: 'smell', title: '建立你的调查工作表' },
  {
    id: 'l4-practice-02-code',
    chapter: 'smell',
    title: '亲手读入，再核对三列',
  },
  { id: 'l4-analyze-cover', chapter: 'analyze', title: '切：分析嫌疑' },
  { id: 'l4-plan', chapter: 'analyze', title: '先排好调查步骤' },
  { id: 'l4-split', chapter: 'analyze', title: '先把名字拆开' },
  { id: 'l4-explode', chapter: 'analyze', title: '让每个恶魔各占一行' },
  { id: 'l4-group', chapter: 'analyze', title: '同一个名字，放到一组' },
  { id: 'l4-aggregate', chapter: 'analyze', title: '一组数字，怎样概括？' },
  { id: 'l4-mean', chapter: 'analyze', title: '计算每组的平均威胁值' },
  { id: 'l4-rank', chapter: 'analyze', title: '谁值得优先调查？' },
  { id: 'l4-trap', chapter: 'analyze', title: '排在第一，就能结案吗？' },
  { id: 'l4-count', chapter: 'analyze', title: '这个平均值来自几次记录？' },
  { id: 'l4-filter', chapter: 'analyze', title: '改变条件，再看调查名单' },
  { id: 'l4-save', chapter: 'analyze', title: '从战报到名单：切的全过程' },
  {
    id: 'l4-practice-03',
    chapter: 'analyze',
    title: '下一轮进攻前，锁定调查方向',
  },
  {
    id: 'l4-practice-03-code',
    chapter: 'analyze',
    title: '一页完成你的数据调查',
  },
  {
    id: 'l4-challenge-entry',
    chapter: 'analyze',
    title: '数据破魔盾：魔王换身了',
  },
  { id: 'l4-summary', chapter: 'analyze', title: '带走一套调查方法' },
] as const;
