export const assetBase = '/courses/ai-with-python/lesson-03';
export const chapters = [
  { id: 'start', number: '00', title: '电影馆的旧档案' },
  { id: 'read', number: '01', title: '断网危机：找回电影档案' },
  { id: 'write', number: '02', title: '勇士换班：情报不能丢！' },
  { id: 'organize', number: '03', title: '恶魔来袭：让档案派上用场！' },
  { id: 'finish', number: '04', title: '城堡档案官' },
] as const;
export const scenes = [
  { id: 'l3-cover', chapter: 'start', title: '探险家的日记本' },
  { id: 'l3-movie-story', chapter: 'read', title: '今晚的电影，谁来介绍？' },
  { id: 'l3-read-cover', chapter: 'read', title: '断网危机：找回电影档案' },
  { id: 'l3-files', chapter: 'read', title: '网页，也能存进文件' },
  {
    id: 'l3-file-concept',
    chapter: 'read',
    title: '文件：给信息一个保存的地方',
  },
  { id: 'l3-read-steps', chapter: 'read', title: '读文件，像借阅一份档案' },
  { id: 'l3-path', chapter: 'read', title: '同一份档案，两种找法' },
  { id: 'l3-read-code', chapter: 'read', title: '打开、读取、自动关闭' },
  { id: 'l3-parse', chapter: 'read', title: '老方法，读出新资料' },
  { id: 'l3-practice-01', chapter: 'read', title: '这次，获取更多电影信息' },
  { id: 'l3-practice-01-read', chapter: 'read', title: '一口气读出电影资料' },
  { id: 'l3-handoff-story', chapter: 'write', title: '下一班勇士，也需要情报' },
  { id: 'l3-write-cover', chapter: 'write', title: '勇士换班：情报不能丢！' },
  { id: 'l3-screen-file', chapter: 'write', title: '写文件，像存入一份新档案' },
  { id: 'l3-write-code', chapter: 'write', title: '同样三步，把“读”换成“写”' },
  { id: 'l3-modes', chapter: 'write', title: '借阅旧档案，还是重新写？' },
  {
    id: 'l3-write-lines',
    chapter: 'write',
    title: '写了两次，为什么挤在一行？',
  },
  { id: 'l3-newline', chapter: 'write', title: '档案太大，一次读完会怎样？' },
  { id: 'l3-practice-02', chapter: 'write', title: '制作勇士交接记录' },
  {
    id: 'l3-practice-02-source',
    chapter: 'write',
    title: '写好交接记录，逐行读取核对',
  },
  { id: 'l3-rescue-story', chapter: 'organize', title: '通信中断，档案仍在' },
  {
    id: 'l3-organize-cover',
    chapter: 'organize',
    title: '恶魔来袭：让档案派上用场！',
  },
  { id: 'l3-lines', chapter: 'organize', title: '读回档案，逐条核对' },
  { id: 'l3-csv', chapter: 'organize', title: '同一份情报，按列排整齐' },
  { id: 'l3-csv-code', chapter: 'organize', title: '把情报写成 CSV 文件' },
  { id: 'l3-practice-03', chapter: 'organize', title: '制作自己的勇士图鉴' },
  { id: 'l3-workshop', chapter: 'organize', title: '把情报表变成勇士图鉴' },
  { id: 'l3-challenge-entry', chapter: 'finish', title: '守住城堡档案室' },
  { id: 'l3-challenge', chapter: 'finish', title: '城堡档案官' },
  { id: 'l3-checkpoint', chapter: 'finish', title: '给下一班勇士留一份档案' },
  { id: 'l3-checkpoint-02', chapter: 'finish', title: '让档案变成你的作品' },
  { id: 'l3-summary', chapter: 'finish', title: '带走一套保存情报的方法' },
] as const;
