"""Build reproducible lesson 05 data, notebook and package without network access."""

import csv
import hashlib
import json
from pathlib import Path
import random
import subprocess
import zipfile
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "public/courses/ai-with-python/lesson-05/practice"
LESSON = ROOT / "app/courses/ai-with-python/lesson-05"
KINDS = ["炎角兽族", "藤甲魔族", "冰翼魔族"]
PENGUIN_KINDS = {"Adelie": "阿德利企鹅", "Chinstrap": "帽带企鹅", "Gentoo": "巴布亚企鹅"}
PENGUIN_SOURCE = "Penguins_cleaned.csv"
PENGUIN_FIELDS = {"billLength": "culmen_length_mm", "billDepth": "culmen_depth_mm",
                  "flipper": "flipper_length_mm", "mass": "body_mass_g"}
SEED = 20261005


def write_csv(name, rows):
    with (OUT / name).open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def build_data():
    rng = random.Random(SEED)
    demons = []
    for individual in range(30):
        for group, (height_mean, speed_mean, mass_mean) in enumerate(
            [(161, 7.6, 71), (197, 5.4, 113), (140, 10.2, 47)]
        ):
            height = round(rng.gauss(height_mean, 18), 1)
            speed = round(max(1.2, min(15.4, speed_mean - (height - height_mean) * 0.015 + rng.gauss(0, 1.65))), 1)
            mass = round(max(24, mass_mean + (height - height_mean) * 0.6 + rng.gauss(0, 12)), 1)
            demons.append({"id": f"D{len(demons) + 1:03}", "kind": KINDS[group],
                           "height": height, "speed": speed, "mass": mass})
    # Intentional exceptions prevent a probabilistic tendency becoming an absolute rule.
    demons[0].update(height=180.0, speed=6.2, mass=86.0)
    demons[3].update(height=205.0, speed=11.7, mass=101.0)
    patrol = [{"hour": hour, "speed": speed} for hour, speed in
              zip([8, 10, 12, 14, 16, 18], [6.2, 7.4, 8.1, 6.9, 5.8, 6.5])]
    # Extend the same day and observation times with one individual per other kind.
    # D001 is copied from the original patrol, never regenerated or averaged.
    kind_patrol = [{"id": "D001", "kind": demons[0]["kind"], **row} for row in patrol]
    for individual, speeds in [("D002", [5.9, 5.3, 4.8, 5.6, 6.4, 5.7]),
                               ("D009", [8.3, 8.9, 7.8, 7.1, 8.2, 9.4])]:
        kind = next(d["kind"] for d in demons if d["id"] == individual)
        kind_patrol.extend({"id": individual, "kind": kind, "hour": row["hour"], "speed": speed}
                           for row, speed in zip(patrol, speeds))
    with (OUT / PENGUIN_SOURCE).open(encoding="utf-8-sig", newline="") as handle:
        original = list(csv.DictReader(handle))
    penguins = []
    for index, row in enumerate(original, 1):
        if any(row[key] in ("", "NA", "NaN") for key in PENGUIN_FIELDS.values()):
            raise ValueError(f"{PENGUIN_SOURCE} row {index} has a missing numeric measurement")
        penguins.append({"id": f"P{index:03}", "kind": PENGUIN_KINDS[row["species"]],
                         "species": row["species"], "island": row["island"],
                         "sex": row["sex"] if row["sex"] not in ("", "NA", "NaN") else None,
                         **{key: float(row[value]) for key, value in PENGUIN_FIELDS.items()}})
    write_csv("demons.csv", demons)
    write_csv("patrol.csv", patrol)
    write_csv("patrol-by-kind.csv", kind_patrol)
    # Retire the previous adapters from the current package; Git retains their history.
    for legacy in ("penguins.csv", "penguins-original.csv"):
        (OUT / legacy).unlink(missing_ok=True)
    types = """// Generated by scripts/build-lesson05-practice.py from the packaged CSV data.
export type Demon = { id: string; kind: string; height: number; speed: number; mass: number };
export type Penguin = { id: string; kind: string; species: string; island: string; sex: string | null; billLength: number; billDepth: number; flipper: number; mass: number };
"""
    for name, annotation, rows in [
        ("demonKinds", "string[]", KINDS), ("demons", "Demon[]", demons),
        ("patrol", "{ hour: number; speed: number }[]", patrol),
        ("kindPatrol", "{ id: string; kind: string; hour: number; speed: number }[]", kind_patrol),
        ("penguinKinds", "string[]", list(PENGUIN_KINDS.values())),
        ("penguins", "Penguin[]", penguins),
    ]:
        types += f"export const {name}: {annotation} = {json.dumps(rows, ensure_ascii=False, indent=2)};\n"
    histograms = {}
    for field in ("height", "speed", "mass"):
        counts, edges = np.histogram([d[field] for d in demons], bins="auto")
        histograms[field] = [{"low": float(edges[i]), "high": float(edges[i + 1]), "count": int(count)}
                             for i, count in enumerate(counts)]
    types += "export const demonHistograms = " + json.dumps(histograms, indent=2) + ";\n"
    (LESSON / "study-data.ts").write_text(types, encoding="utf-8")
    stats = {
        "seed": SEED, "demonCount": len(demons), "penguinSource": PENGUIN_SOURCE,
        "penguinSourceCount": len(original), "penguinCount": len(penguins),
        "penguinSourceSha256": hashlib.sha256((OUT / PENGUIN_SOURCE).read_bytes()).hexdigest(),
        "penguinMissingSexCount": sum(row["sex"] in ("", "NA", "NaN") for row in original),
        "demonSpeedBins": histograms["speed"],
        "demonMeans": {kind: {field: round(sum(d[field] for d in demons if d["kind"] == kind) / 30, 2)
                              for field in ("height", "speed", "mass")} for kind in KINDS},
        "penguinCounts": {kind: sum(p["kind"] == kind for p in penguins) for kind in PENGUIN_KINDS.values()},
    }
    (OUT / "data-summary.json").write_text(json.dumps(stats, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return stats


def load_codes():
    result = subprocess.run(
        ["node", "--experimental-strip-types", "--input-type=module", "--eval",
         f"import * as source from {json.dumps((LESSON / 'practice-content.ts').as_uri())}; "
         "process.stdout.write(JSON.stringify(source));"], capture_output=True, text=True, check=True)
    return json.loads(result.stdout)


def markdown(text):
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(True)}


def blank():
    return {"cell_type": "code", "metadata": {"tags": ["student-input"]},
            "execution_count": None, "outputs": [], "source": []}


def build():
    OUT.mkdir(parents=True, exist_ok=True)
    stats = build_data()
    code = load_codes()
    intro = """# 第五课：勇闯图表世界

## 恶魔军团图鉴 → 企鹅家族研究
魔王已经现身。侦察队新增了 90 个恶魔个体的观测，勇士需要一份有证据的图鉴。
前两个课堂练习研究恶魔。第三小节先观察恶魔种类的特征线索，再比较真实企鹅数据，最后跟写企鹅分类展示代码。

## 开始前
1. 安装 Python 3.10 或更高版本，在终端运行 `python -m pip install -r requirements.txt`。
2. 解压整个练习包，在这个文件夹运行 `python -m jupyterlab`，打开 `第五课练习.ipynb`。
3. CSV、笔记本与完整参考文件放在同一个文件夹；先跟写并运行准备代码，再依次完成练习。笔记本开头的中文字体单元格已预置，只需运行。
4. 在空白代码单元亲手输入，按 Shift + Enter 运行。完整参考放在末尾，用来核对。

英文坐标名后的括号是单位。恶魔种类使用中文；企鹅种类沿用原文件的 Adelie、Chinstrap、Gentoo。
若中文显示为方框，安装 Noto Sans CJK SC
或将预置环境代码中的字体名称改为系统已有中文字体，再从准备代码开始重新运行。
没有图时检查是否运行 `plt.show()`；提示变量不存在时先运行准备代码。

## 读懂数据
- `demons.csv`：90 行，每行一个不同个体；三族各 30 个。`id` 是档案编号，`kind` 是种类；
  `height` 是自然直立时身高（cm），`speed` 是相同平地测量条件下的速度（m/s），`mass` 是体重（kg）。
  这是教学模拟的新增个体观测，不是第四课的进攻事件，也不是把威胁值改名。
- `patrol.csv`：同一个体 **D001** 在同一天 8、10、12、14、16、18 时的速度观测，
  仍在相同测量场地和方法下测量。`hour` 是时刻，`speed` 单位 m/s；不是六只不同恶魔。
- `patrol-by-kind.csv`：承接 D001 的原六次记录，新增藤甲魔族 D002、冰翼魔族 D009
  在同一天、同一时刻的教学模拟观测，共 18 行。`id` 是个体编号，`kind` 是种类。
  第 28 页以颜色区分种类，每条折线仍追踪同一个体；三个个体的记录不能代表整族。
- `Penguins_cleaned.csv`：老师提供的 342 条真实企鹅记录，保持文件原有字段和行序。
  `species` 是已知种类（Adelie 阿德利、Chinstrap 帽带、Gentoo 巴布亚），`island` 是观测岛屿；
  `culmen_length_mm` 喙长（mm）、`culmen_depth_mm` 喙深（mm）、
  `flipper_length_mm` 鳍肢长度（mm）、`body_mass_g` 体重（g），`sex` 是性别。
  四项数值完整；9 条性别缺失仍保留，当前绘图不需要性别。
  企鹅体重使用 g，恶魔体重使用 kg，不要直接混用。

种类内有差异，种类间会重叠；两项特征有关联，不代表其中一项造成另一项。
"""
    tasks = [
        ("课堂练习 01 · 看清速度分布", "HIST_CODE",
         "先猜哪些速度常见，再跟写直方图。每根柱子表示一个速度区间里有多少个体；由 seaborn 自动分组。通常左含右不含，最后一区间含右端点。",
         "指出人数最多的区间，并用柱高写出数量；区分‘一个速度区间’和‘一个恶魔’。"),
        ("课堂练习 02 · 三个例子，亲手画出三种图", "PRACTICE_02_CODE",
         "先跟写并运行共用准备代码，再依次输入三段绘图代码，每格按 Shift + Enter 运行。共用准备只写一次：读取 demons.csv 与 patrol.csv。散点图观察 90 个恶魔的身高与速度；折线图追踪 D001 的一天；条形图比较三族的平均速度。",
         "依次画出三种图，核对各自的坐标、单位和数据。用散点图观察两项特征的联系，用折线图找出 D001 速度变化，用条形图比较三族平均速度；说清每张图回答的问题。"),
        ("课堂练习 03 · 画出企鹅的种类差异", "PENGUIN_PRACTICE_CODE",
         "先运行预置字体单元格，再亲手输入完整代码，读取 Penguins_cleaned.csv，画出喙长与喙深散点图，并用 hue=\"species\" 按已知种类着色。按 Shift + Enter 运行，核对输出图。",
         "图上包含 342 个观测点；横轴为 Bill length (mm)，纵轴为 Bill depth (mm)，图例包含三种企鹅。说出一种类别特点，并指出不同种类之间会重叠。"),
    ]
    font_cell = blank()
    font_cell["source"] = code["FONT_CODE"].splitlines(True)
    font_cell["metadata"] = {"tags": ["environment-setup"]}
    cells = [markdown(intro), markdown("## 中文显示环境（已预置）\n直接运行下一格，不需要跟写；之后完成准备代码。"), font_cell, markdown("## 准备代码\n先跟写并运行，读取恶魔个体档案。\n```python\n" + code["SETUP_CODE"] + "\n```"), blank()]
    for title, key, instruction, standard in tasks:
        if key == "PENGUIN_PRACTICE_CODE":
            cells += [
                markdown("## 教师演示参考 · 恶魔种类与特征线索\n在 90 个恶魔的身高与速度图上加入种类颜色，再换一组特征观察。藤甲魔族整体较高、较重，平均速度较低；冰翼魔族整体较矮、较轻，平均速度较高。D004 身高 205 cm、速度 11.7 m/s，是高且快的例外。\n```python\n" + code["HUE_CODE"] + "\n```"),
                markdown("## 教师演示参考 · 企鹅四项特征的关系总览\n先比较真实企鹅的喙长、喙深、鳍肢长度与体重，再进入跟写练习。两个维度相同的对角格看单项分布，其余格子用散点图看两项特征的联系。\n\n未着色时，对角线使用直方图：\n```python\n" + code["PAIRPLOT_UNCOLORED_FULL_CODE"] + "\n```\n\n按已知种类着色后，对角线自动使用密度图；曲线越高，该值附近的记录越集中，不能把曲线高度读成只数。所有格子与后面的练习使用同一份 342 条观测。\n```python\n" + code["PAIRPLOT_FULL_CODE"] + "\n```"),
            ]
        cells.append(markdown(f"## {title}\n{instruction}\n\n完成标准：{standard}"))
        if key == "PRACTICE_02_CODE":
            cells += [markdown("### 共用准备 · 只写一次\n先运行预置字体单元格，再跟写以下代码。两份 CSV 与笔记本放在同一文件夹。\n```python\n" + code["PRACTICE_02_PREPARATION"] + "\n```"), blank()]
            for step, reference in enumerate(code["PRACTICE_02_PLOTS"], 1):
                cells += [markdown(f"### 步骤 {step} · {reference['title']}\n{reference['question']}\n在已运行共用准备的同一笔记本中跟写：\n```python\n" + reference["code"] + "\n```"), blank()]
            cells.append(markdown("练习收获：散点图观察个体的身高与速度联系；折线图发现 D001 在 12 时这次观测中最快、16 时最慢；条形图看清三族平均速度，冰翼魔族最高，藤甲魔族最低。\n\n不同问题适合不同的图。联系不等于因果，六次巡逻记录不代表整族，种类平均值也不代表每一个体；勇士还要继续侦察。"))
        else:
            cells += [markdown("跟写参考：\n```python\n" + code[key] + "\n```"), blank()]
        if key == "PENGUIN_PRACTICE_CODE":
            cells.append(markdown("练习收获：阿德利企鹅的喙通常较短；帽带与巴布亚企鹅的喙长相近，但帽带企鹅的喙通常更深。不同种类的点仍有重叠，仅凭一项或两项数值不能保证认出每一只企鹅。"))
        cells.append(markdown("我的发现：\n\n图中的证据：\n\n还想调查："))
    cells += [markdown("## 教师观察参考 · 切换企鹅特征\n课堂上可在喙长、喙深、鳍肢长度与体重之间选择两个数值维度，再比较着色前后的点群。读取同一份 Penguins_cleaned.csv，修改 x、y 对应的原文件字段与坐标标签；hue=\"species\" 表示已知种类。这里是在观察数据，不是训练自动识别模型。\n```python\n" + code["PENGUIN_FULL_CODE"] + "\n```"),
              markdown("## 教师演示参考 · 比较五个个体\n每根柱子是一只恶魔，柱高是身高。\n```python\n" + code["BAR_CODE"] + "\n```"),
              markdown("## 教师演示参考 · 身高与速度\n一个点对应一个恶魔，观察两项数值的联系，也寻找例外。\n```python\n" + code["SCATTER_CODE"] + "\n```"),
              markdown("## 教师演示参考 · 同一个体的一天\n先读取同一只 D001 的六次记录，按时间顺序连接。线段帮助观察变化，未测量时刻的精确数值仍未知。\n```python\n" + code["LINE_CODE"] + "\n```"),
              markdown("## 教师演示参考 · 三族的平均速度\n一根柱子对应一个种类；seaborn 默认计算该类个体的平均速度，errorbar=None 隐藏误差线。这是三族平均值，不代表每只恶魔的速度。\n```python\n" + code["KIND_BAR_FULL_CODE"] + "\n```"),
              markdown("## 完整参考\n运行顺序：准备、五个个体条形图、练习 01、散点图演示、折线图演示、三族条形图演示、练习 02 三图、恶魔种类演示、企鹅关系总览、练习 03 企鹅种类散点图。\n```python\n" + code["COMPLETE_CODE"] + "\n```")]
    for index, cell in enumerate(cells):
        cell["id"] = f"lesson05-{index:03}"
    notebook = {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                "language_info": {"name": "python", "version": "3.10"}}, "nbformat": 4, "nbformat_minor": 5}
    (OUT / "第五课练习.ipynb").write_text(json.dumps(notebook, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (OUT / "完整参考.py").write_text(code["COMPLETE_CODE"] + "\n", encoding="utf-8")
    (OUT / "课堂练习二完整参考.py").write_text(code["PRACTICE_02_CODE"] + "\n", encoding="utf-8")
    (OUT / "requirements.txt").write_text("pandas>=2.2,<4\nseaborn>=0.13,<0.14\nmatplotlib>=3.8,<4\njupyterlab>=4,<5\n", encoding="utf-8")
    sources = f"""
## 企鹅来源与处理
数据由 Kristen Gorman 博士及 Palmer Station Antarctica LTER 收集，由
[palmerpenguins 官方项目](https://allisonhorst.github.io/palmerpenguins/)整理发布，许可为 **CC0**。
本课使用老师于 2026-10-09 提供的 `Penguins_cleaned.csv`，练习包保留原文件字节，
不改字段、测量数值、行序或种类名称。许可全文在 `PENGUINS-LICENSE.md`。
当前文件 SHA-256：`{stats['penguinSourceSha256']}`。

提供的文件已有 342 行，四项数值完整；其中 9 条性别缺失，当前图表不使用性别，因此全部保留。
网页按文件行序生成 P001–P342 作为观察编号，将数值字段适配为展示字段，并提供中文种类名。
学生 Python、笔记本、参考代码直接读取原字段；species 是种类，包含 Adelie 151 条、Chinstrap 68 条、Gentoo 123 条。
所有课堂企鹅图与下载使用同一份文件，不另生成学生用的改名版 CSV。

引用：Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data.
[DOI: 10.5281/zenodo.3960218](https://doi.org/10.5281/zenodo.3960218)。
原研究：Gorman KB, Williams TD, Fraser WR (2014),
[Ecological Sexual Dimorphism and Environmental Variability within a Community of Antarctic Penguins](https://doi.org/10.1371/journal.pone.0090081)。

## 核对与文件
三个课堂练习依次是：
1. 用直方图看清 90 只恶魔的速度分布。
2. 围绕三个问题跟写三种图：90 个恶魔的身高与速度联系、D001 的一天变化、三族的平均速度比较。
3. 在观察恶魔与企鹅的种类线索后，跟写企鹅喙长与喙深的分类散点图。完整代码包含导入、读取 CSV、按 species 着色、坐标标签和显示图形。
   核对 342 个点、两个坐标的名称与单位、三种企鹅的图例，并说出一种类别特点和种类间的重叠。
第三小节的教学顺序是恶魔种类与特征线索、企鹅四项特征关系总览、企鹅喙部特征讲解、课堂练习 03。
企鹅特征的下拉切换与着色观察已融合到课堂讲解，帮助比较不同维度；课后练习仍按课件中的任务完成。

笔记本提供三个课堂练习、空白跟写格和末尾参考。`完整参考.py` 可在练习文件夹通过
`python 完整参考.py` 运行，依次出现十一张输出图，每次关闭图窗后继续；JupyterLab 会将图放在单元格下方。
`课堂练习二完整参考.py` 读取 `demons.csv` 与 `patrol.csv`，依次绘制身高与速度散点图、D001 巡逻折线图、三族平均速度条形图。网页练习二分为跟写和核对两页；第一页同时展示共用准备与三段绘图代码，第二页展示三个输出与收获。笔记本同样提供共用准备和三个绘图单元：先运行字体设置，再跟写准备代码一次，之后依次跟写三段绘图代码。
每张图均为真实 CSV 的绘图结果；图的默认配色与网页教学演示可能不同。
企鹅关系总览使用 `sns.pairplot`，明确选择 culmen_length_mm、culmen_depth_mm、flipper_length_mm、body_mass_g 四个数值字段，沿用默认对角图类型：未着色用直方图，按 species 着色后用密度图。网页的高斯核密度估计与 Seaborn 默认参数一致，使用 Scott 带宽、200 个采样点、两端延伸三个带宽、各类共同归一化；曲线高度不是只数。4×4 矩阵其余十二格是两两散点图，每格均使用同一份 342 条观测。
课堂练习 03 的坐标为 Bill length (mm) 与 Bill depth (mm)，species 是已知种类。课堂观察可以修改横纵轴；它不涉及训练分类模型。
`data-summary.json` 提供数量与区间统计。`reference-plots/` 是验证程序执行同一份代码保存的十一张输出图，其中一张是 16 格企鹅关系总览。
恶魔数据使用固定随机种子 {SEED} 生成；D004 是身高 205 cm、速度 11.7 m/s 的高个体快速度例子。
数据包含人为设置的教学例外，不能用模拟恶魔数据推断真实生物规律。
直方图使用 seaborn 默认自动分组；网页根据同一数据和 NumPy 的默认 auto 方法生成区间与数量。
区间通常左含右不含，最后一区间包含右端点。网页坐标刻度为便于阅读作了四舍五入，数量按原始边界统计。
可重复运行各绘图单元。若之前留下未关闭的图，先运行 `plt.close("all")` 再重画。
"""
    (OUT / "README.md").write_text(intro + sources, encoding="utf-8")
    subprocess.run([str(ROOT / "node_modules/.bin/oxfmt"), str(LESSON / "study-data.ts"),
                    str(OUT / "README.md"), str(OUT / "data-summary.json")],
                   check=True, capture_output=True, text=True)
    with zipfile.ZipFile(OUT / "lesson-05-practice.zip", "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(OUT.rglob("*")):
            if path.is_file() and path.suffix != ".zip" and "__pycache__" not in path.parts:
                archive.write(path, path.relative_to(OUT))
    print(json.dumps(stats, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    build()
