"""Build lesson 03's notebook and offline samples from practice-content.ts."""

from html import escape
import json
from pathlib import Path
import subprocess
import zipfile


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "public/courses/ai-with-python/lesson-03/practice"
SOURCE = ROOT / "app/courses/ai-with-python/lesson-03/practice-content.ts"


def load_source():
    """Node handles TypeScript formatting; the data has one maintained source."""
    result = subprocess.run(
        [
            "node",
            "--experimental-strip-types",
            "--input-type=module",
            "--eval",
            f"import {{ practiceSource }} from {json.dumps(SOURCE.as_uri())}; "
            "process.stdout.write(JSON.stringify(practiceSource));",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def markdown(text):
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(True)}


def code(text="", **metadata):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": metadata,
        "outputs": [],
        "source": text.splitlines(True),
    }


def exercise(title, instruction, reference, expected=None, expected_label="运行后核对"):
    """Students type into blank cells; references are readable Markdown only."""
    cells = [
        markdown(f"### {title}\n{instruction}\n\n完整参考：\n```python\n{reference}\n```"),
        code("", tags=["student-input"]),
    ]
    if expected is not None:
        cells.append(markdown(f"{expected_label}：\n```text\n{expected}\n```"))
    return cells


def build():
    source = load_source()
    codes = source["codes"]
    file_task = source["homework"]["file"]
    atlas_task = source["homework"]["atlas"]
    homework_readme = "\n".join((
        f"- CHECKPOINT 01 · {file_task['title']}：{file_task['instruction']}"
        f"{file_task['tip']}完成标准：{' '.join(file_task['evidence'])}{file_task['variation']}",
        f"- CHECKPOINT 02 · {atlas_task['title']}：{atlas_task['instruction']}"
        f"{atlas_task['tip']}作品方向：{' '.join(atlas_task['directions'])}"
        f"完成标准：{atlas_task['evidence']}",
    ))
    OUT.mkdir(parents=True, exist_ok=True)
    generated = []

    def write(name, text):
        path = OUT / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        generated.append(path)

    for movie in source["movies"]:
        actors = "\n".join(
            f'  <a rel="v:starring">{escape(actor)}</a>'
            for actor in movie["actors"]
        )
        html = f'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(movie["title"])} · 教学节选</title>
<style>
body {{ margin: 0; padding: 24px; background: #fffaf0; color: #142a46; font: 20px/1.6 system-ui, sans-serif; }}
h1 {{ margin: 12px 0; font-size: 32px; }}
p {{ margin: 12px 0; }}
a[rel="v:starring"] {{ display: inline-block; margin-right: 12px; }}
strong[property="v:average"] {{ color: #9a5500; font-weight: 700; }}
a {{ color: #165e9c; }}
</style>
</head>
<body>
<p>电影详情教学节选；演员仅列部分，评分沿用第二课保存样本。</p>
<h1><span property="v:itemreviewed">{escape(movie["title"])}</span></h1>
<p>导演：<a rel="v:directedBy">{escape(movie["director"])}</a></p>
<div>演员：
{actors}
</div>
<p>评分：<strong property="v:average">{escape(movie["score"])}</strong></p>
<p>资料来源：<a href="{escape(movie["source"])}">豆瓣电影条目</a>；HTML 为课堂节选，保留详情页的标签与属性。</p>
</body>
</html>
'''
        write(movie["path"], html)
        if movie["id"] == "1292052":
            write("film_1292052.html", html)
        # Remove only the superseded files generated by the previous package.
        old_path = OUT / f"samples/movies/{movie['id']}.html"
        if old_path.exists():
            old_path.unlink()

    write("samples/intel-archive.txt", source["archive"])
    write("requirements.txt", "beautifulsoup4>=4.12,<5\n")
    references = "\n\n".join(
        f"## {movie['title']}\n\n"
        f"- 来源：[豆瓣电影条目]({movie['source']})\n"
        f"- 导演：{movie['director']}\n"
        f"- 本样本所列演员：{'、'.join(movie['actors'])}\n"
        f"- 评分：{movie['score']}（第二课 2026-09-08 保存样本值）"
        for movie in source["movies"]
    )
    write(
        "SOURCES.md",
        "# 样本来源\n\n"
        "本练习提供第二课使用过的三部电影，供选择并替换文件路径。"
        "电影详情字段在 2026-09-22 通过豆瓣公开条目的搜索索引核对；"
        "直接打开条目遇到站点验证，没有绕过验证或继续发送抓取请求。"
        "电影评分沿用第二课保存的节选，不代表实时评分。"
        "只保留标题、导演、部分演员、评分；HTML 是根据核对后字段整理的教学结构，"
        "不是网站完整源代码。\n\n"
        + references
        + "\n\n敌情样本沿用课程故事：炎角兽在北方峡谷、怕强光；"
        "藤甲魔在迷雾森林、怕火；冰翼魔在冰封山口、怕热。"
        "记录描述保存时的已知情报，不表示恶魔的实时位置。\n",
    )
    write(
        "README.md",
        f"""# 第三课：探险家的日记本

电影资料能从文件里读出来，守城情报也能保存下来、交给伙伴继续使用。

## 开始前

1. 使用 Python 3.10 或以上和 JupyterLab。解压整个练习包。
2. 在解压后的 `lesson-03-practice` 文件夹中打开“第三课练习.ipynb”。
3. 第一次使用时，在 Notebook 的准备单元格运行 `%pip install -r requirements.txt`。
4. 按课堂顺序，在空白 Code 单元格亲手输入完整参考代码，再按 Shift + Enter 运行。

安装依赖可能需要联网；安装成功后的文件练习全部离线完成。若提示找不到文件，
先在 JupyterLab 左侧确认 `film_1292052.txt` 和 Notebook 位于同一个文件夹。
本课的相对路径 `./film_1292052.txt` 从程序当前工作文件夹出发；
按上述方式打开 Notebook 时，这里就是练习包文件夹。

## 课堂练习与完成标准

- CHECKLIST 01：在一个代码单元格中完成读取文件、解析 HTML、输出片名、导演、评分和演员；与样本核对一致。
- CHECKLIST 02：在代码中定义 `reports` 列表，把三条情报写入 `handover.txt`，再用 `for line in f` 逐行读取核对。文件与输出都有三条情报，每条一行，没有多余空行。
- CHECKLIST 03：向 AI 提供 `handover.csv`，选择风格并发送创作要求。核对图鉴有三张卡片、资料准确，支持按名称搜索。

## 课后练习与完成标准

{homework_readme}

电影原始资料是 Notebook 旁的 `film_1292052.txt`、`film_1291546.txt`、`film_1292722.txt`。
这些 `.txt` 文件保存的是 HTML 源码，Python 读取后再用 BeautifulSoup 解析。
`film_1292052.html` 与同名 `.txt` 内容完全相同，供浏览器打开并呈现网页；
直接打开 `.txt` 通常看到的是源码，不会自动呈现为网页。
敌情原始资料在 `samples/`。所有写入代码使用新的输出文件：`handover.txt`、
`handover.csv`、`line-break-test.txt`、`overwrite-test.txt`。它们在运行时生成，不随练习包预先提供。
重复以 `w` 打开同一个已有文件会先清空旧内容，再写入本次内容。
课堂观察覆盖效果使用 `overwrite-test.txt`。课后只在自己文件的测试副本上再次用 `w` 打开，
先预测旧内容会怎样，再验证。保留正式作品和原始样本，不要把输出路径改成它们。

`with` 代码块结束时会关闭文件。`write()` 不会自动换行，所以每条记录后加 `\\n`。
`for line in f` 每次取得一行；`readlines()` 会把全部行放进列表，不能用来说明节省内存。
CSV 使用 `csv.DictWriter` 处理字段和分隔符，并在打开文件时设置 `newline=""`。

## 输出对照

`handover.txt` 应有三行：

```text
"""
        + source["reportOutput"]
        + "\n```\n\n`handover.csv` 应有四行：\n\n```csv\n"
        + source["csvPreview"]
        + "\n```\n\n电影样本与出处见 `SOURCES.md`。演员为节选，评分是保存值。"
        "本课把电影阅读方法迁移到敌情读写；演员重复计数留作后续数据分析思考。\n",
    )

    cells = [
        markdown(
            "# 第三课：探险家的日记本\n"
            "先读电影资料，再把方法用于守城情报。每一步都在空白 Code 单元格亲手输入，"
            "按 Shift + Enter 运行。完整参考在每格上方；完成后核对输出和文件。\n\n"
            "请在解压后的练习包文件夹打开本 Notebook，保持它与 `film_1292052.txt` 在同一个文件夹。"
        ),
        markdown("## 准备\n安装一次依赖；后面的文件读写全部离线运行。"),
        code("%pip install -r requirements.txt", tags=["setup"]),
        markdown(
            "## CHECKLIST 01 · 从电影文件找回资料\n"
            "管理员保存了三份电影详情。先读取 `./film_1292052.txt`，完成后可换成 "
            "`./film_1291546.txt` 或 `./film_1292722.txt`，重新运行整个代码单元格。"
            "txt 文件保存的是 HTML 源码；演员只列部分，评分是保存值。"
        ),
    ]
    cells += exercise(
        "01 · 读取文件，解析电影资料",
        "在下方一个空白代码单元格中亲手输入完整流程，再按 Shift + Enter 运行。"
        "路径从程序当前工作文件夹开始，文件与 Notebook 放在一起。"
        "完成标准：片名、导演、评分和两位演员都与样本一致。",
        codes["MOVIE_COMPLETE_CODE"],
        source["movies"][0]["output"],
    )
    cells += exercise(
        "观察 · 连续写入会自己换行吗？",
        "亲手输入完整代码并运行，再从 JupyterLab 左侧打开 line-break-test.txt。"
        "先观察：调用两次 write()，文件里的两段文字会占几行？"
        "写文件没有 print，输出区为空是正常的；核对的是实际文件内容。",
        codes["WRITE_JOINED_LINES"],
        source["joinedLines"],
        expected_label="文件内容示例",
    )
    cells += exercise(
        "观察 · 加上 \\n 再写一次",
        "亲手输入完整代码并运行，再打开同一份 line-break-test.txt。"
        "两段文字各加上 \\n 后，核对它们是否各占一行。"
        "w 会清空上一步的测试内容。写文件没有 print，输出区为空是正常的。",
        codes["WRITE_SEPARATE_LINES"],
        source["separateLines"],
        expected_label="文件内容示例",
    )
    cells += [markdown(
        "## CHECKLIST 02 · 给接班勇士留下情报\n"
        "勇士即将换班，把已知的三条情报存进交接文件，让下一班勇士逐行读取核对。"
    )]
    cells += exercise(
        "02 · 写好交接记录，逐行读取核对",
        "在下方空白代码单元格中亲手输入完整代码，从上到下运行。"
        "先定义 reports 列表，将三条情报写入 ./handover.txt，再用 for line in f 逐行读取。"
        "完成标准：文件与输出都有三条情报，每条一行，没有多余空行。"
        "w 会覆盖同名交接文件。",
        codes["REPORT_COMPLETE_CODE"],
        source["reportOutput"],
    )
    cells += exercise(
        "观察 · 第一份测试记录",
        "只在 overwrite-test.txt 中测试。先写入第一份记录，再去下一格预测结果。",
        codes["OVERWRITE_FIRST"],
    )
    cells += exercise(
        "观察 · 再用 w 打开会怎样？",
        "先猜：最后会留下几行？再输入、运行并核对。w 打开已有文件时会先清空旧内容。",
        codes["OVERWRITE_SECOND"],
        "第二份记录",
    )
    cells += exercise(
        "观察 · 一次读一行",
        "使用同一份 handover.txt，换成逐行读取。end=\"\" 让 print 不再额外添一个换行。",
        codes["LINE_BY_LINE"],
        source["reportOutput"],
    )
    cells += [markdown(
        "## 代码讲解参考 · 将情报整理成 CSV\n"
        "每行一个恶魔，每列一种信息。一个字典就是一条带字段名的记录；"
        "列表保存三条记录。本课先看懂并跟写，不进行字典计数。"
    )]
    cells += exercise(
        "参考 · 生成城堡情报表",
        "从上到下亲手输入完整代码并运行，打开生成的 handover.csv。"
        "核对三列、一行表头和三条情报，没有多余空行。"
        "写文件没有 print，输出区为空是正常的；下面是文件内容示例。"
        "csv 模块随 Python 提供，不需要另外安装。",
        codes["WRITE_CSV"],
        source["csvPreview"],
        expected_label="文件内容示例",
    )
    cells += exercise(
        "拓展 · 重新读取表格并核对",
        "逐条打印字段；确认三条记录没有串列，也没有额外空行。",
        codes["READ_CSV"],
        "\n".join(" ".join((r["name"], r["location"], r["weakness"])) for r in source["intel"]),
    )
    cells += [markdown(
        "## CHECKLIST 03 · 制作自己的勇士图鉴\n"
        "向老师指定的 AI 工具手动上传 handover.csv 文件。"
        "从下面的要求中选填风格，再发送给 AI。\n\n"
        + source["aiPrompt"]
        + "\n\n完成标准：三张卡片、资料准确、按名称搜索可用。"
    )]
    cells += [
        markdown(
            f"## CHECKPOINT 01 · {file_task['title']}\n"
            f"{file_task['question']}\n\n{file_task['instruction']}\n{file_task['tip']}\n\n"
            "完成后拿出这些证据：\n\n"
            + "\n".join(f"- {item}" for item in file_task["evidence"])
            + f"\n\n再试一个变化：{file_task['variation']}\n保留正式文件和原始样本。"
        ),
        code("", tags=["student-input"]),
        markdown(
            f"## CHECKPOINT 02 · {atlas_task['title']}\n"
            f"{atlas_task['question']}\n\n{atlas_task['instruction']}\n{atlas_task['tip']}\n\n"
            "任选一种创作方向，也可以提出自己的展示方式：\n\n"
            + "\n".join(f"- {direction}" for direction in atlas_task["directions"])
            + "\n\n"
            "给 AI 的要求可以这样写，再按自己的想法修改：\n\n"
            "请根据我提供的 CSV 文件制作一页【图鉴 / 交接看板 / 地图旁资料卡 / 自定：____】网页。"
            "请保留原表中的字段与信息，文字清楚，让伙伴方便地查找记录。"
            "风格和布局用：____。\n\n"
            f"完成标准：{atlas_task['evidence']}"
        ),
        markdown(
            "## 下一课的思考\n"
            "如果有更多电影记录，怎样找到评分最高的电影？怎样统计某位演员出现了几次？"
            "本课的文件保存好了，下一课可以接着分析。"
        ),
    ]
    for index, cell in enumerate(cells):
        cell["id"] = f"lesson03-cell-{index:02d}"
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    write("第三课练习.ipynb", json.dumps(notebook, ensure_ascii=False, indent=2) + "\n")
    with zipfile.ZipFile(OUT / "lesson-03-practice.zip", "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(generated):
            info = zipfile.ZipInfo("lesson-03-practice/" + path.relative_to(OUT).as_posix())
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, path.read_bytes())
    print(f"Built lesson-03-practice.zip with {len(generated)} files; no runtime output included.")


if __name__ == "__main__":
    build()
